/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/mentorship': typeof MentorshipRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/mentorship': typeof MentorshipRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/mentorship': typeof MentorshipRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/community'
    | '/events'
    | '/jobs'
    | '/learning'
    | '/mentorship'
    | '/notifications'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/success-stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/community'
    | '/events'
    | '/jobs'
    | '/learning'
    | '/mentorship'
    | '/notifications'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/success-stories'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/community'
    | '/events'
    | '/jobs'
    | '/learning'
    | '/mentorship'
    | '/notifications'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/success-stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  JobsRoute: typeof JobsRoute
  LearningRoute: typeof LearningRoute
  MentorshipRoute: typeof MentorshipRoute
  NotificationsRoute: typeof NotificationsRoute
  ResourcesRoute: typeof ResourcesRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  JobsRoute: JobsRoute,
  LearningRoute: LearningRoute,
  MentorshipRoute: MentorshipRoute,
  NotificationsRoute: NotificationsRoute,
  ResourcesRoute: ResourcesRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
